name: environment
dependencies:
- pip >= 9
- python = 3.5.0
- jupyter
- numpy
- scipy
- scikit-learn
- pandas
- matplotlib
- bokeh
- menpo::opencv3
- pip:
  - jupyter==1.0.0
  - matplotlib==1.5.3
  - numpy==1.11.2
  - tensorflow >= 0.12.0rc1
  - scikit-learn==0.18
  - scipy==0.18.1
  - pillow==3.4.2